name: PR

on:
  pull_request:
    branches:
      - main
permissions:
  contents: read 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Tests
        run: echo "Running tests on PR"

      - name: Trigger Workflow Run
        run: echo "Triggering subsequent workflow"
